/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DemoGradle;

import java.util.ArrayList;
import java.util.Scanner;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
//    public static void main(String[] args) {
//    	Scanner scan=new Scanner(System.in);
//    	4
//    	ArrayList list=new ArrayList();
//    	list.add(12);
//    	list.add(13);
//    	System.out.println(list);
//    }
}
